[package]
name = "raytracing-in-a-weekend-rust"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.29.0" # https://github.com/dimforge
rand = "0.8.4"